version: "3.8"

services:

  mongodb:
    image: mongo:6.0.4
    container_name: mongodb
    ports:
      - "27017:27017"
    healthcheck:
      test: echo 'db.stats().ok' | mongosh localhost:27017/moviesdb --quiet

  postgres:
    image: postgres:15.2
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: "pg_isready -U postgres"

  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL_HOST=postgres
      - KC_DB_URL_DATABASE=keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=password
      - KC_HEALTH_ENABLED=true
    ports:
      - "8080:8080"
    command: start-dev
    depends_on:
      - postgres
    healthcheck:
      test: "curl -f http://localhost:8080/health/ready || exit 1"

  movies-api:
    image: ghcr.io/skyglass-movie/movies-online-api:1ccba0d20a18ffcc40a43d708e98720513bd1841
    container_name: movies-api
    environment:
      - SERVER_PORT=9080
      - SPRING_KEYCLOAK_SERVER_URL=http://keycloak:8080
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/moviesdb
    ports:
      - "9080:9080"
    depends_on:
      - postgres
      - keycloak

  movies-ui:
    image: ghcr.io/skyglass-movie/movies-online-ui:6aff98503b4087ba5f0da115a636eadd84a189a6
    container_name: movies-ui
    ports:
      - "80:80"
    depends_on:
      - postgres
      - keycloak
      - movies-api       
