spring:
  redis:
    host: polar-redis
    username: user
    password: default
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://polar-keycloak/realms/PolarBookshop
